name: nxade_music
description: N-Xade Music - A simple, elegant and open source music player by N-Xade Studios

publish_to: 'none'

version: 1.12.1+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  just_audio: ^0.9.40
  audio_service: ^0.18.12
  material_design_icons_flutter: ^7.0.7296
  flutter_gradient_colors: ^2.0.0
  cached_network_image: ^3.3.1
  audiotags: ^1.4.5
  just_audio_background: ^0.0.1-beta.17
  flutter_phoenix: ^1.1.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.6+1
  google_mobile_ads: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/notification_logo.png
    - assets/licenses/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 26  # Android 8.1 (API level 26)
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"