LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := NXadeMusic
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := N-Xade Music.apk
LOCAL_MODULE_CLASS := APKS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Music MusicPlayer
include $(BUILD_PREBUILT)
